test error message

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -51,3 +51,8 @@ jobs:
     steps:
       - name: Run Mint
         run: mint -vv asafsamuel/workflow-test:latest
+
+      - name: Validate environment variables
+        run: 
+          echo "::error::API_KEY is missing"
+          exit 1
